name: cd_docker

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> "$GITHUB_ENV"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish Docker SemVer Tag
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: keweizhang/flagr
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        platforms: linux/amd64,linux/arm64
        tags: "latest"
